version: '3'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}/php
    container_name: ${PROJECT_NAME}_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  # NGINX Service
  web:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_web
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/letsencrypt/:/etc/nginx/letsencrypt/
    ports:
        - "80:80"
        - "443:443"
  # MYSQL Service
  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

# Elasticsearch service
  es01:
    image: elasticsearch:7.17.7
    container_name: ${PROJECT_NAME}_es01
    restart: unless-stopped
    tty: true
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

# DOCKER Volumes
volumes:
  db:
    driver: local
